config/routes.rb
Rails.application.routes.draw do
  devise_for :companies,  controllers: {
    sessions: 'companies/sessions',
    registrations: 'companies/registrations'
  }
  devise_for :jobseekers,  controllers: {
    sessions: 'jobseekers/sessions',
    registrations: 'jobseekers/registrations'
  }

  root to: 'pages#home'

  resources :offers, only: [:index, :show] do
    resources :candidacies, only: [:create]
  end

  resources :candidacies, only: [:index, :show]

  namespace :company do
    resources :offers
    resources :candidacies, only: [:show]
  end

end

app/models/candidacy.rb
class Candidacy < ApplicationRecord
  belongs_to :jobseeker
  belongs_to :offer
end

app/controllers/candidacies_controller.rb
class CandidaciesController < ApplicationController
  skip_before_action :authenticate_company!

  def index
    @candidacies = Candidacy.where(jobseeker_id: current_jobseeker.id)
  end

  def show
    @candidacy = Candidacy.find(params[:id])
  end

  def create
    @candidacy = Candidacy.new(candidacy_params)
    @candidacy.jobseeker_id = current_jobseeker.id
    @candidacy.save
    flash[:notice] = "Candidature envoyée !"
    redirect_to candidacies_path
  end

  private

  def candidacy_params
    params.permit(:offer_id, :jobseeker_id)
  end
end

app/controllers/company/candidacies_controller.rb
class Company::CandidaciesController < ApplicationController
  skip_before_action :authenticate_jobseeker!

  def show
    @candidacy = Candidacy.find(params[:id])
  end
end

app/views/candidacies/index.html.erb
<div class="page">
  <div class="container text-center">
    <h4>Mes candidatures</h4>
  </div>
  <div class="container">
    <% if @candidacies != [] %>
      <div class="dashbord">
        <% @candidacies.each do |candidacy| %>
          <%= link_to candidacy_path(candidacy.id) do %>
            <div class="message">
              <div class="message-name">
                <h3><strong><%= candidacy.offer.job_name || candidacy.offer.formation_name %></strong></h3>
                <p><%= candidacy.created_at.day %>/<%= candidacy.created_at.month %>/<%= candidacy.created_at.year %></p>
              </div>
              <div class="message-body hidden-xs">
                <p><%= candidacy.offer.company.name %></p>
                <p><%= candidacy.offer.company.sector %></p>
              </div>
              <div class="message-status">
                <% if candidacy.offer.job? %>
                  <p class="status emploi">Emploi</p>
                <% else %>
                  <p class="status formation">Formation</p>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% else %>
      <h4>Vous avez aucune candidature en cours</h4>
    <% end %>
  </div>
</div>

app/views/candidacies/show.html.erb
<div class="page">
  <div class="container">
    <h4><%= @candidacy.offer.job_name || @candidacy.offer.formation_name %></h4>
    <h6><%= @candidacy.offer.company.name %></h6>

    <%= link_to "Retour", candidacies_path, class: "btn btn-primary" %>
  </div>
</div>