config/routes.rb
Rails.application.routes.draw do
  devise_for :companies,  controllers: {
    sessions: 'companies/sessions',
    registrations: 'companies/registrations'
  }
  devise_for :jobseekers,  controllers: {
    sessions: 'jobseekers/sessions',
    registrations: 'jobseekers/registrations'
  }

  root to: 'pages#home'

  resources :offers, only: [:index, :show] do
    resources :candidacies, only: [:create]
  end

  resources :candidacies, only: [:index, :show]

  namespace :company do
    resources :offers
    resources :candidacies, only: [:show]
  end

end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :offers, dependent: :destroy
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :company
  has_many :candidacies, dependent: :destroy

  include PgSearch
  pg_search_scope :search_offers,
    against: [:formation_name, :formation_description, :job_name, :job_description],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/companies/confirmations_controller.rb
# frozen_string_literal: true

class Companies::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/companies/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Companies::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/companies/passwords_controller.rb
# frozen_string_literal: true

class Companies::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/companies/registrations_controller.rb
# frozen_string_literal: true

class Companies::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/companies/sessions_controller.rb
# frozen_string_literal: true

class Companies::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/companies/unlocks_controller.rb
# frozen_string_literal: true

class Companies::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
end

app/controllers/company/candidacies_controller.rb
class Company::CandidaciesController < ApplicationController
  skip_before_action :authenticate_jobseeker!

  def show
    @candidacy = Candidacy.find(params[:id])
  end
end

app/controllers/company/offers_controller.rb
class Company::OffersController < ApplicationController
  skip_before_action :authenticate_jobseeker!

  def index
    @jobs = Offer.where(company_id: current_company.id, job: true)
    @formations = Offer.where(company_id: current_company.id, job: false)
    @offer = Offer.new
  end

  def show
    @offer = Offer.find(params[:id])
    @candidacies = Candidacy.where(offer_id: @offer)
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.company_id = current_company.id
    @offer.save
    redirect_to edit_company_offer_path(@offer)
  end

  def edit
    @offer = Offer.find(params[:id])
  end

  def update
    @offer = Offer.find(params[:id])
    @offer.update(offer_params)
    redirect_to company_offers_path
  end

  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy
    redirect_to company_offers_path
  end

  private

  def offer_params
    params.require(:offer).permit(:job,
                                  :required_profile,
                                  :date_start,
                                  :formation_name,
                                  :formation_description,
                                  :degree,
                                  :price,
                                  :job_name,
                                  :job_description,
                                  :contract)
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  skip_before_action :authenticate_jobseeker!, only: [:index, :show]
  skip_before_action :authenticate_company!, only: [:index, :show]

  def index
    if params[:query].present?
      @results = Offer.search_offers(params[:query])
    else
      @jobs = Offer.where(job: true)
      @formations = Offer.where(job: false)
    end
  end

  def show
    @offer = Offer.find(params[:id])
  end
end

app/views/company/offers/edit.html.erb
<div class="container">
  <%= simple_form_for [:company, @offer] do |f| %>
    <% if @offer.job == true %>
      <%= f.input :job_name %>
      <%= f.input :job_description %>
      <%= f.input :required_profile %>
      <%= f.input :contract %>
      <%= f.input :date_start, as: :date %>
    <% end %>
    <% if @offer.job == false %>
      <%= f.input :formation_name %>
      <%= f.input :formation_description %>
      <%= f.input :required_profile %>
      <%= f.input :degree %>
      <%= f.input :price %>
      <%= f.input :date_start, as: :date %>
    <% end %>
      <%= f.submit 'Save', class: "btn btn-primary btn-block" %>
  <% end %>
</div>

app/views/company/offers/index.html.erb
<div class="container">
  <div class="text-center">
    <h1><%= current_company.name %></h1>
    <h4><%= current_company.sector %></h4>
    <p><%= current_company.description %></p>
  </div>
  <br>
  <div>
    <% if @jobs != [] %>
      <h4>Liste de vos offres d'emploies</h4>
      <div class="dashbord">
        <% @jobs.each do |job| %>
          <%= link_to company_offer_path(job.id) do %>
            <div class="message">
              <div class="message-name">
                <h3><strong><%= job.job_name %></strong></h3>
              </div>
              <div class="message-body hidden-xs">
                <p><%= job.job_description %></p>
              </div>
              <div class="message-status">
                <p><%= job.contract %></p>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>

    <% if @formations != [] %>
      <h4>Liste de vos formations</h4>
      <div class="dashbord">
        <% @formations.each do |formation| %>
          <%= link_to company_offer_path(formation.id) do %>
            <div class="message">
              <div class="message-name">
                <h3><strong><%= formation.formation_name %></strong></h3>
              </div>
              <div class="message-body hidden-xs">
                <p><%= formation.formation_description %></p>
              </div>
              <div class="message-status">
                <p><%= formation.degree %></p>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
  <br>
  <div class="text-center">
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
      Creer une nouvelle offre
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-body">
            <div>
              <%= simple_form_for [:company, @offer] do |f| %>
                <%= f.input :job,:as => :boolean, :input_html => { :checked => "checked" } %>
                <%= f.button :submit, "Offre d'emploi", class: 'btn btn-danger btn-block' %>
              <% end %>
            </div>
            <div>
              <%= simple_form_for [:company, @offer] do |f| %>
                <%= f.input :job,:as => :boolean, :input_html => { :checked => "unchecked" } %>
                <%= f.button :submit, "Offre de formation", class: 'btn btn-danger btn-block' %>
              <% end %>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary btn-block" data-dismiss="modal">Annuler</button>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br>
  <div class=text-center>
    <%= link_to "Acceuil", root_path, class: "btn btn-default" %>
  </div>
</div>

app/views/company/offers/show.html.erb
<div class="container">
  <div class="text_center">
    <h2><%= @offer.job_name || @offer.formation_name %> #<%= @offer.id %></h2>
    <h4><%= @offer.job_description || @offer.formation_description %></h4>
  </div>

  <div class="dashbord">
    <% @candidacies.each do |candidacy| %>
      <%= link_to company_candidacy_path(candidacy.id) do %>
        <div class="message">
          <img class="avatar-large" src="https://fnadepape.org/wp-content/uploads/2018/07/avatar-1577909_960_720.png">
          <div class="message-name">
            <h3><strong><%= candidacy.jobseeker.first_name %>
            <%= candidacy.jobseeker.last_name %></strong></h3>
          </div>
          <div class="message-body hidden-xs">
            <p>
              <%= candidacy.jobseeker.profession %>
              -
              <%= candidacy.jobseeker.address %>
            </p>
          </div>
          <div class="message-status">
            <p>Contacter</p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="text-center">
    <%= link_to 'Supprimer', company_offer_path(@offer), method: :delete, class: "btn btn-default" %>
    <%= link_to 'Retour', company_offers_path, class: "btn btn-primary" %>
  </div>
</div>