config/routes.rb
Rails.application.routes.draw do
  devise_for :companies,  controllers: {
    sessions: 'companies/sessions',
    registrations: 'companies/registrations'
  }
  devise_for :jobseekers,  controllers: {
    sessions: 'jobseekers/sessions',
    registrations: 'jobseekers/registrations'
  }

  root to: 'pages#home'

  resources :offers, only: [:index, :show] do
    resources :candidacies, only: [:create]
  end

  resources :candidacies, only: [:index, :show]

  namespace :company do
    resources :offers
    resources :candidacies, only: [:show]
  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <p>@sauveteurs-nautiques</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">

  <!-- JOBSEEKER NAVBAR -->
  <% if jobseeker_signed_in? %>
    <!-- Left Navigation -->
    <div class="navbar-wagon-left hidden-xs">
      <div class="navbar-wagon-item">
        <!-- Avatar -->
        <%= image_tag "https://fnadepape.org/wp-content/uploads/2018/07/avatar-1577909_960_720.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu" %>
        <!-- Menu -->
        <%= link_to "Rechercher", offers_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "Candidatures", candidacies_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "Profil", edit_jobseeker_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "Deconnexion", destroy_jobseeker_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>
      </div>
    </div>

    <!-- Dropdown list MOBILE -->
    <div class="navbar-wagon-left">
      <div class="navbar-wagon-item hidden-sm hidden-md hidden-lg">
        <div class="dropdown">
          <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
          <ul class="dropdown-menu navbar-wagon-dropdown-menu">
            <li><a href="#">Rechercher</a></li>
            <li><a href="#">Candidatures</a></li>
            <li><%= link_to "Profil", edit_jobseeker_registration_path %></li>
            <li>
              <%= link_to "Deconnexion", destroy_jobseeker_session_path, method: :delete, class: "navbar-wagon-link" %>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="navbar-wagon-right">
      <!-- LOGO -->
      <div class="navbar-wagon-item hidden-sm hidden-md hidden-lg">
        <a href="/" class="navbar-wagon-brand">
          <img src="https://i.etsystatic.com/16575763/r/il/e9aa6e/1640248840/il_570xN.1640248840_a4lh.jpg" alt="logo">
        </a>
      </div>
    </div>

    <!-- LOGO -->
    <div class="navbar-wagon-right hidden-xs">
      <div class="navbar-wagon-item">
        <a href="/" class="navbar-wagon-brand">
          <img src="https://i.etsystatic.com/16575763/r/il/e9aa6e/1640248840/il_570xN.1640248840_a4lh.jpg" alt="logo">
        </a>
      </div>
    </div>


  <!-- COMPANY NAVBAR -->
  <% elsif company_signed_in? %>

    <!-- LOGO -->
    <div class="navbar-wagon-left">
      <a href="/" class="navbar-wagon-brand">
        <img src="https://i.etsystatic.com/16575763/r/il/e9aa6e/1640248840/il_570xN.1640248840_a4lh.jpg" alt="logo">
      </a>
    </div>

    <div class="navbar-wagon-right hidden-xs">
      <div class="navbar-wagon-item">
        <!-- Menu -->
        <%= link_to "Tableau de bord", company_offers_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "Profil", edit_company_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "Deconnexion", destroy_company_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>
        <!-- Avatar -->
        <%= image_tag "https://fnadepape.org/wp-content/uploads/2018/07/avatar-1577909_960_720.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu" %>
      </div>
    </div>
    <!-- Dropdown list MOBILE -->
    <div class="navbar-wagon-item hidden-sm hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Tableau de bord", company_offers_path %></li>
          <li><%= link_to "Profil", edit_company_registration_path %></li>
          <li>
            <%= link_to "Deconnexion", destroy_company_session_path, method: :delete, class: "navbar-wagon-link" %>
          </li>
        </ul>
      </div>
    </div>


  <!-- NO CONNECTED NAVBAR -->
  <% else %>
    <!-- Login link (Jobseeker) -->
    <div class="hidden-xs">
      <%= link_to t(".sign_in", default: "Espace Sauveteur"), new_jobseeker_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    </div>
    <div class="hidden-sm hidden-md hidden-lg">
      <%= link_to new_jobseeker_session_path, class: "navbar-wagon-item navbar-wagon-link" do %>
        <i class="fas fa-user"></i>
      <% end %>
    </div>
    <!-- Logo -->
    <div>
      <a href="/" class="navbar-wagon-brand">
        <img src="https://i.etsystatic.com/16575763/r/il/e9aa6e/1640248840/il_570xN.1640248840_a4lh.jpg" alt="logo">
      </a>
    </div>
    <!-- Login link (Company) -->
    <div class="hidden-xs">
      <%= link_to t(".sign_in", default: "Espace Société"), new_company_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    </div>
    <div class="hidden-sm hidden-md hidden-lg">
      <%= link_to new_company_session_path, class: "navbar-wagon-item navbar-wagon-link" do %>
        <i class="fas fa-user-tie"></i>
      <% end %>
    </div>
  <% end %>
</div>