config/routes.rb
Rails.application.routes.draw do
  devise_for :companies,  controllers: {
    sessions: 'companies/sessions',
    registrations: 'companies/registrations'
  }
  devise_for :jobseekers,  controllers: {
    sessions: 'jobseekers/sessions',
    registrations: 'jobseekers/registrations'
  }

  root to: 'pages#home'

  resources :offers, only: [:index, :show] do
    resources :candidacies, only: [:create]
  end

  resources :candidacies, only: [:index, :show]

  namespace :company do
    resources :offers
    resources :candidacies, only: [:show]
  end

end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :company
  has_many :candidacies, dependent: :destroy

  include PgSearch
  pg_search_scope :search_offers,
    against: [:formation_name, :formation_description, :job_name, :job_description],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/company/offers_controller.rb
class Company::OffersController < ApplicationController
  skip_before_action :authenticate_jobseeker!

  def index
    @jobs = Offer.where(company_id: current_company.id, job: true)
    @formations = Offer.where(company_id: current_company.id, job: false)
    @offer = Offer.new
  end

  def show
    @offer = Offer.find(params[:id])
    @candidacies = Candidacy.where(offer_id: @offer)
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.company_id = current_company.id
    @offer.save
    redirect_to edit_company_offer_path(@offer)
  end

  def edit
    @offer = Offer.find(params[:id])
  end

  def update
    @offer = Offer.find(params[:id])
    @offer.update(offer_params)
    redirect_to company_offers_path
  end

  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy
    redirect_to company_offers_path
  end

  private

  def offer_params
    params.require(:offer).permit(:job,
                                  :required_profile,
                                  :date_start,
                                  :formation_name,
                                  :formation_description,
                                  :degree,
                                  :price,
                                  :job_name,
                                  :job_description,
                                  :contract)
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  skip_before_action :authenticate_jobseeker!, only: [:index, :show]
  skip_before_action :authenticate_company!, only: [:index, :show]

  def index
    if params[:query].present?
      @results = Offer.search_offers(params[:query])
    else
      @jobs = Offer.where(job: true)
      @formations = Offer.where(job: false)
    end
  end

  def show
    @offer = Offer.find(params[:id])
  end
end

app/views/offers/index.html.erb
<div class="container">
  <h1>Toutes les offres</h1>

  <%= form_tag offers_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Trouver une offre"
    %>
  <% end %>
<!-- Resultat recherche -->

  <div class="row">
    <% if @results != nil %>
      <% @results.each do |result| %>
        <% if result.job? %>
          <div class="col-xs-12 col-sm-4">
            <%= link_to offer_path(result.id) do %>
              <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://images.pexels.com/photos/5399/beach-sand-lifeguard.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260');">
                <div class="card-category">Emploi</div>
                <div class="card-description">
                  <h2><%= result.job_name %></h2>
                  <p><%= result.company.place %></p>
                </div>
                <div class="card-user"><%= result.company.name %></div>
              </div>
            <% end %>
          </div>
        <% else %>
          <div class="col-xs-12 col-sm-4">
            <%= link_to offer_path(result.id) do %>
              <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://images.pexels.com/photos/2687/sea-beach-sand-ocean.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260');">
                <div class="card-category">Formation</div>
                <div class="card-description">
                  <h2><%= result.formation_name %></h2>
                  <p><%= result.company.place %></p>
                </div>
                <div class="card-user"><%= result.company.name %></div>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>

<!-- Toutes les offres -->

  <div class="row">
    <% if @jobs != nil %>
      <h2 class="text-center">Offres d'emploies</h2>
      <% @jobs.each do |job| %>
        <div class="col-xs-12 col-sm-4">
          <%= link_to offer_path(job.id) do %>
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://images.pexels.com/photos/5399/beach-sand-lifeguard.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260');">
              <div class="card-category">Emploi</div>
              <div class="card-description">
                <h2><%= job.job_name %></h2>
                <p><%= job.company.place %></p>
              </div>
              <div class="card-user"><%= job.company.name %></div>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="row">
    <% if @formations != nil %>
    <h2 class="text-center">Formations</h2>
      <% @formations.each do |formation| %>
        <div class="col-xs-12 col-sm-4">
          <%= link_to offer_path(formation.id) do %>
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://images.pexels.com/photos/2687/sea-beach-sand-ocean.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260');">
              <div class="card-category">Formation</div>
              <div class="card-description">
                <h2><%= formation.formation_name %></h2>
                <p><%= formation.company.place %></p>
              </div>
              <div class="card-user"><%= formation.company.name %></div>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/offers/show.html.erb
<% if @offer.job == true %>
  <div class="wrapper" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://images.pexels.com/photos/5399/beach-sand-lifeguard.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260');">
    <div class="container text-center">
      <h1><%= @offer.job_name %></h1>
      <h4><%= @offer.company.name %></h4>
    </div>
  </div>
  <div class="container text-center">
      <p><%= @offer.job_description %></p>
      <p><%= @offer.contract %></p>
      <p><%= @offer.required_profile %></p>
      <p><%= @offer.date_start %></p>
  </div>
<% else %>
  <div class="wrapper" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://images.pexels.com/photos/2687/sea-beach-sand-ocean.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260');">
    <div class="container text-center">
      <h1><%= @offer.formation_name %></h1>
      <h4><%= @offer.company.name %></h4>
    </div>
  </div>
  <div class="container text-center">
      <p><%= @offer.formation_description %></p>
      <p><%= @offer.degree %></p>
      <p><%= @offer.price %>€</p>
      <p><%= @offer.required_profile %></p>
      <p><%= @offer.date_start %></p>
  </div>
<% end %>
<div class="container text-center">
  <% unless company_signed_in? %>
    <p><%= link_to "Candidater", offer_candidacies_path(@offer), method: :post, class: "btn btn-secondary" %></p>
  <% end %>
  <p><%= link_to "Retour", offers_path, class: "btn btn-primary" %></p>
</div>